apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-1
    litmuschaos.io/chaos: true
  name: nginx-1
  namespace: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - command:
        - /agnhost
        - netexec
        - --http-port
        - "8080"
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        name: nginx-1-container
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: nginx-1
spec:
  clusterIP: 10.108.52.177
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8085
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-1
  sessionAffinity: None
  type: LoadBalancer
