apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: e042f872-cc89-4871-8b93-9bd2180812f8
    subject: nginx-1-mem-suck_litmus
    workflow_id: 585811d5-2456-4247-a4d3-0cba4e5abf23
    workflows.argoproj.io/controller-instanceid: e042f872-cc89-4871-8b93-9bd2180812f8
  name: nginx-1-mem-suck-1686003433
  namespace: litmus
spec:
  concurrencyPolicy: Forbid
  schedule: 24 0-23 * * *
  startingDeadlineSeconds: 0
  timezone: America/Los_Angeles
  workflowMetadata:
    creationTimestamp: null
    labels:
      cluster_id: e042f872-cc89-4871-8b93-9bd2180812f8
      workflow_id: 585811d5-2456-4247-a4d3-0cba4e5abf23
      workflows.argoproj.io/controller-instanceid: e042f872-cc89-4871-8b93-9bd2180812f8
  workflowSpec:
    arguments:
      parameters:
      - name: adminModeNamespace
        value: litmus
    entrypoint: custom-chaos
    podGC:
      strategy: OnWorkflowSuccess
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
    - inputs: {}
      metadata: {}
      name: custom-chaos
      outputs: {}
      steps:
      - - arguments: {}
          name: install-chaos-experiments
          template: install-chaos-experiments
      - - arguments: {}
          name: pod-memory-hog-tka
          template: pod-memory-hog-tka
    - container:
        args:
        - kubectl apply -f /tmp/pod-memory-hog-tka.yaml -n {{workflow.parameters.adminModeNamespace}}
          &&  sleep 30
        command:
        - sh
        - -c
        image: litmuschaos/k8s:3.0.0-beta3
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-memory-hog-tka
          path: /tmp/pod-memory-hog-tka.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              description:
                message: |
                  Injects memory consumption on pods belonging to an app deployment
              kind: ChaosExperiment
              metadata:
                name: pod-memory-hog
                labels:
                  name: pod-memory-hog
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: chaosexperiment
                  app.kubernetes.io/version: 3.0.0-beta3
              spec:
                definition:
                  scope: Namespaced
                  permissions:
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - deletecollection
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - pods/log
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods/exec
                      verbs:
                        - get
                        - list
                        - create
                    - apiGroups:
                        - apps
                      resources:
                        - deployments
                        - statefulsets
                        - replicasets
                        - daemonsets
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - apps.openshift.io
                      resources:
                        - deploymentconfigs
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - ""
                      resources:
                        - replicationcontrollers
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - argoproj.io
                      resources:
                        - rollouts
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - batch
                      resources:
                        - jobs
                      verbs:
                        - create
                        - list
                        - get
                        - delete
                        - deletecollection
                    - apiGroups:
                        - litmuschaos.io
                      resources:
                        - chaosengines
                        - chaosexperiments
                        - chaosresults
                      verbs:
                        - create
                        - list
                        - get
                        - patch
                        - update
                        - delete
                  image: litmuschaos/go-runner:3.0.0-beta3
                  imagePullPolicy: Always
                  args:
                    - -c
                    - ./experiments -name pod-memory-hog
                  command:
                    - /bin/bash
                  env:
                    - name: TOTAL_CHAOS_DURATION
                      value: "60"
                    - name: MEMORY_CONSUMPTION
                      value: "500"
                    - name: NUMBER_OF_WORKERS
                      value: "1"
                    - name: PODS_AFFECTED_PERC
                      value: ""
                    - name: RAMP_TIME
                      value: ""
                    - name: LIB_IMAGE
                      value: litmuschaos/go-runner:3.0.0-beta3
                    - name: STRESS_IMAGE
                      value: alexeiled/stress-ng:latest-ubuntu
                    - name: CONTAINER_RUNTIME
                      value: docker
                    - name: SOCKET_PATH
                      value: /var/run/docker.sock
                    - name: SEQUENCE
                      value: parallel
                    - name: TARGET_PODS
                      value: ""
                    - name: NODE_LABEL
                      value: ""
                  labels:
                    name: pod-memory-hog
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: experiment-job
                    app.kubernetes.io/runtime-api-usage: "true"
                    app.kubernetes.io/version: 3.0.0-beta3
      metadata: {}
      name: install-chaos-experiments
      outputs: {}
    - container:
        args:
        - -file=/tmp/chaosengine-pod-memory-hog-tka.yaml
        - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:3.0.0-beta3
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-memory-hog-tka
          path: /tmp/chaosengine-pod-memory-hog-tka.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                namespace: "{{workflow.parameters.adminModeNamespace}}"
                generateName: pod-memory-hog-tka
                labels:
                  workflow_run_id: "{{workflow.uid}}"
                  workflow_name: nginx-1-mem-suck-1686003433
              spec:
                engineState: active
                appinfo:
                  appns: nginx-1
                  applabel: app=nginx-1
                  appkind: deployment
                chaosServiceAccount: litmus-admin
                experiments:
                  - name: pod-memory-hog
                    spec:
                      components:
                        env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "300"
                          - name: MEMORY_CONSUMPTION
                            value: "1000"
                          - name: PODS_AFFECTED_PERC
                            value: "100"
                          - name: CONTAINER_RUNTIME
                            value: docker
                          - name: SOCKET_PATH
                            value: /var/run/docker.sock
                      probe:
                        - name: nginx-1-http
                          type: httpProbe
                          mode: Continuous
                          runProperties:
                            probeTimeout: 1000
                            retry: 0
                            interval: 1
                            probePollingInterval: 1
                            stopOnFailure: true
                          httpProbe/inputs:
                            url: http://nginx-1.nginx-1.svc.cluster.local:8085/hostname
                            insecureSkipVerify: true
                            method:
                              get:
                                criteria: ==
                                responseCode: "200"
                annotationCheck: "true"
      metadata:
        labels:
          weight: "10"
      name: pod-memory-hog-tka
      outputs: {}
status:
  active: null
  conditions: null
  lastScheduledTime: null
