apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: foo-pod-probe-hopeful-1685061679
  namespace: default
  labels:
    subject: foo-pod-probe-hopeful_default
spec:
  schedule: 3 0-23 * * *
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments:
      parameters:
        - name: adminModeNamespace
          value: default
    entrypoint: custom-chaos
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
      - name: custom-chaos
        steps:
          - - name: install-chaos-experiments
              template: install-chaos-experiments
          - - name: pod-delete-hdp
              template: pod-delete-hdp
      - name: install-chaos-experiments
        inputs:
          artifacts:
            - name: pod-delete-hdp
              path: /tmp/pod-delete-hdp.yaml
              raw:
                data: >
                  apiVersion: litmuschaos.io/v1alpha1

                  description:
                    message: |
                      Deletes a pod belonging to a deployment/statefulset/daemonset
                  kind: ChaosExperiment

                  metadata:
                    name: pod-delete
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: chaosexperiment
                      app.kubernetes.io/version: 3.0.0-beta3
                  spec:
                    definition:
                      scope: Namespaced
                      permissions:
                        - apiGroups:
                            - ""
                          resources:
                            - pods
                          verbs:
                            - create
                            - delete
                            - get
                            - list
                            - patch
                            - update
                            - deletecollection
                        - apiGroups:
                            - ""
                          resources:
                            - events
                          verbs:
                            - create
                            - get
                            - list
                            - patch
                            - update
                        - apiGroups:
                            - ""
                          resources:
                            - configmaps
                          verbs:
                            - get
                            - list
                        - apiGroups:
                            - ""
                          resources:
                            - pods/log
                          verbs:
                            - get
                            - list
                            - watch
                        - apiGroups:
                            - ""
                          resources:
                            - pods/exec
                          verbs:
                            - get
                            - list
                            - create
                        - apiGroups:
                            - apps
                          resources:
                            - deployments
                            - statefulsets
                            - replicasets
                            - daemonsets
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - apps.openshift.io
                          resources:
                            - deploymentconfigs
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - ""
                          resources:
                            - replicationcontrollers
                          verbs:
                            - get
                            - list
                        - apiGroups:
                            - argoproj.io
                          resources:
                            - rollouts
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - batch
                          resources:
                            - jobs
                          verbs:
                            - create
                            - list
                            - get
                            - delete
                            - deletecollection
                        - apiGroups:
                            - litmuschaos.io
                          resources:
                            - chaosengines
                            - chaosexperiments
                            - chaosresults
                          verbs:
                            - create
                            - list
                            - get
                            - patch
                            - update
                            - delete
                      image: litmuschaos/go-runner:3.0.0-beta3
                      imagePullPolicy: Always
                      args:
                        - -c
                        - ./experiments -name pod-delete
                      command:
                        - /bin/bash
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "15"
                        - name: RAMP_TIME
                          value: ""
                        - name: FORCE
                          value: "true"
                        - name: CHAOS_INTERVAL
                          value: "5"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                        - name: TARGET_PODS
                          value: ""
                        - name: NODE_LABEL
                          value: ""
                        - name: SEQUENCE
                          value: parallel
                      labels:
                        name: pod-delete
                        app.kubernetes.io/part-of: litmus
                        app.kubernetes.io/component: experiment-job
                        app.kubernetes.io/version: 3.0.0-beta3
        container:
          args:
            - kubectl apply -f /tmp/pod-delete-hdp.yaml -n
              {{workflow.parameters.adminModeNamespace}} &&  sleep 30
          command:
            - sh
            - -c
          image: litmuschaos/k8s:3.0.0-beta3
      - name: pod-delete-hdp
        inputs:
          artifacts:
            - name: pod-delete-hdp
              path: /tmp/chaosengine-pod-delete-hdp.yaml
              raw:
                data: >
                  apiVersion: litmuschaos.io/v1alpha1

                  kind: ChaosEngine

                  metadata:
                    namespace: "{{workflow.parameters.adminModeNamespace}}"
                    generateName: pod-delete-hdp
                    labels:
                      workflow_run_id: "{{workflow.uid}}"
                  spec:
                    appinfo:
                      appns: default
                      applabel: app=nginx-2
                      appkind: deployment
                    engineState: active
                    chaosServiceAccount: litmus-admin
                    experiments:
                      - name: pod-delete
                        spec:
                          components:
                            env:
                              - name: TOTAL_CHAOS_DURATION
                                value: "30"
                              - name: CHAOS_INTERVAL
                                value: "10"
                              - name: FORCE
                                value: "false"
                              - name: PODS_AFFECTED_PERC
                                value: ""
                          probe:
                            - name: 'nginx-1-http-probe'
                              type: httpProbe
                              mode: 'Continuous'
                              httpProbe/inputs:
                                url: 'http://nginx-1.nginx-1.svc.cluster.local:8080/hostname'
                                insecureSkipVerify: false
                                responseTimeout: 1000
                                method:
                                  get:
                                    criteria: == 
                                    responseCode: "300"
                              runProperties:
                                probeTimeout: 100
                                interval: 1
                                retry: 1
                                probePollingInterval: 1
        container:
          args:
            - -file=/tmp/chaosengine-pod-delete-hdp.yaml
            - -saveName=/tmp/engine-name
          image: litmuschaos/litmus-checker:3.0.0-beta3
  timezone: America/Los_Angeles
