apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    litmuschaos.io/chaos: "true"
    litmuschaos.io/gitops: "true"
    Litmuschaos.io/workflow: 5b66ab3f-b153-4db1-a8ff-58537c51e387
  labels:
    app: nginx-2
    app.kubernetes.io/version: "1.1.3"
  name: nginx-2
  namespace: nginx-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-2
        app.kubernetes.io/version: "1.1.3"
    spec:
      containers:
      - command:
        - /agnhost
        - netexec
        - --http-port
        - "8080"
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        name: nginx-2-container
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-2
  name: nginx-2
  namespace: nginx-2
spec:
  clusterIP: 10.108.52.178
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8086
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-2
  sessionAffinity: None
  type: LoadBalancer
